# Валидация конфига
# Шаблон `amtool check-config alertmanager.yml`
# Проверка через контейнер без скачивания локально
#   podman cp "/path/to/file/alertmanager/alertmanager.yml" alertmanager_container:/tmp/alertmanager.yml
#   podman exec -it alertmanager_container ls -l /tmp
#   podman exec -it alertmanager_container amtool check-config /tmp/alertmanager.yml
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'ntfy'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'ntfy'
    webhook_configs:
      - url: 'http://ntfy:80/alerts?template=yaml'
        send_resolved: true
