services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.6.15-ubuntu
    volumes:
      # named volume: grafana-data
      - 'grafana-data:/var/lib/grafana'
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # по умолчанию так и есть login admin pass admin
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.5.4
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # bind mount: локальные файлы конфигурации пробрасываются внутрь контейнера
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules/actual_rules:/etc/prometheus/rules:ro
      # named volume: prometheus_data, куда Prometheus пишет свою базу time-series.
      - prometheus_data:/prometheus 
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle" # перезапустить curl -X POST http://localhost:9090/-/reload
    restart: unless-stopped
    networks:
      - monitoring

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.33.0
    volumes:
      - ./prometheus/alerts/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./prometheus/alerts/templates:/etc/alertmanager/templates:ro
    ports:
      - 9093:9093
    environment:
      - '--config.file=/etc/alertmanager/alertmanager.yml' # по умолчанию так и есть. Путь к файлу конфигурации Alertmanager.
      - '--storage.path=/alertmanager' # по умолчанию так и есть. Путь к директории для хранения данных Alertmanager.
      - '--web.listen-address=:9093' # по умолчанию так и есть. Адрес и порт, на которых Alertmanager слушает HTTP-запросы.
      - '--web.route-prefix=/alertmanager' # по умолчанию так и есть. Префикс URL-адреса для Alertmanager.
    networks:
      - monitoring

  # node-exporter - собирает метрики хоста (CPU, память, диск, сеть, файловые системы) и отдаёт их в формате Prometheus по `/metrics`.
  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host" # замапленный /host на read only папку /
    # --web.telemetry-path="/node" - отдавать по url. По умолчанию /metrics
    volumes:
      - /:/host:ro,rslave # мапим / на /host
    restart: unless-stopped
    networks:
      - monitoring
  
  node-exporter2:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter2
    ports:
      - "9101:9100"
    command:
      - "--path.rootfs=/host" # замапленный /host на read only папку /
    # --web.telemetry-path="/node" - отдавать по url. По умолчанию /metrics
    volumes:
      - /:/host:ro,rslave # мапим / на /host
    restart: unless-stopped
    networks:
      - monitoring


  nginx:
    container_name: nginx
    image: nginx:1.31.2
    ports:
      - 8080:80
    volumes:
      - './nginx/server.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: nginx-exporter
    depends_on:
      - nginx
    ports:
      - 9113:9113
    command:
      - '--nginx.scrape-uri=http://nginx:80/stub_status'
    networks:
      - monitoring

  postgres:
    container_name: postgres
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - monitoring

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter:v0.17.1
    depends_on:
      - postgres
    ports:
      - 9187:9187
    environment:
      # подключения к базе: postgresql://<юзер>:<пароль>@<хост>:<порт>/<база данных>
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgres:5432/postgres?sslmode=disable"
    networks:
      - monitoring

  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:v2.11.0
    command:
      - serve
    environment:
      - NTFY_BASE_URL=http://localhost:8888
    ports:
      - 8888:80
    networks:
      - monitoring

volumes:
  prometheus_data: # named volume: Docker создаёт и управляет им сам
  grafana-data:

networks:
  monitoring:
    driver: bridge 